### PR TITLE
Update SSL key

### PR DESCRIPTION
**Pull request by romancewastaken**

### CODE REVIEW

**Comment by WaifuTrash** [comment]
how did u get/calculate this? just wanna be prepared for the next time it happens

**Comment by romancewastaken** [comment]
> how did u get/calculate this? just wanna be prepared for the next time it happens

using the ssl certificate you can get the public key, i thought he used a private one but he uses public so we don't rlly need him to update the key just the certificate

**Comment by TheHellTower** [comment]
> how did u get/calculate this? just wanna be prepared for the next time it happens

Hello, from the moment a website has a certificate and redirect all requests through https along with it you can get it.

The only important thing to remember is every new certificate generated goes along with a new public key.

I just made [this](https://github.com/TheHellTower/Website_SSL_Certificate_Public_Key_Recover) if you are lazy to search a way for it and the Release is [here](https://github.com/TheHellTower/Website_SSL_Certificate_Public_Key_Recover/releases/tag/1.0).

Regards.

**Comment by WaifuTrash** [comment]
thank you guys, that was really useful

**Pull request closed without merging**
